spring:
  application:
    name: GeoPatitas
  datasource:
    # url: jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres
    url: jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres
    username: postgres.csxhblxxunewljrllhvd
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  
geopatitas:
  ai:
    huggingface:
      api-key: ${HUGGINGFACE_API_KEY}
      model-id: sentence-transformers/all-MiniLM-L6-v2
  supabase:
    url: https://csxhblxxunewljrllhvd.supabase.co
    api-key: ${SUPABASE_API_KEY}
    bucket: pets
